<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width,initial-scale=1.0">
  <title>Async Await</title>
  <link rel="stylesheet" href="../base.css">
</head>

<body>
  <script>
    function wait(ms = 0) {
      return new Promise((resolve) => {
        setTimeout(resolve, ms);
      });
    }

    function makePizza(toppings = []) {
      return new Promise(function (resolve, reject) {
        // reject if people try with mayo
        if (toppings.includes('mayonnaise')) {
          reject('Seriously? Get out.');
        }
        const amountOfTimeToBake = 500 + toppings.length * 200;
        // wait 1 second for the pizza to cook:
        setTimeout(function () {
          // when you are ready, you can resolve this promise
          resolve(`Here is your pizza 🍕 with the toppings ${toppings.join(' ')}`);
        }, amountOfTimeToBake);
        // if something went wrong, we can reject this promise;
      });
    }
    function handleError(err) {
      console.log('oh no..');
      console.log(err);
    }

    // async function go() {
    //   // TRY AND CATCH safety blanket
    //   try {
    //     const pizza = await makePizza(['mayonnaise']);

    //     // here you can show an error to the user, log the error in a tracking service, etc.
    //   } catch (err) {
    //     console.log(err);
    //   }
    // }

    // this is also an option to catch and handle errors
    // const pizza = await makePizza(['mayonnaise']).catch(handleError);
    // this is also an option to catch and handle errors

    // IMPORTANT NOTE
    // when you mark a function as ASYNC it will immediately return a PROMISE
    // you can chain THEN and CATCH on it
    // go()
    //   .then((result) => {
    //     console.log(result);
    //   })
    //   .catch(handleError);

    async function go() {
      const pizza = await makePizza(['pineapple']);
      console.log(pizza);
      return pizza;
    }

    // go();

    // you can NEST PROMISES!
    async function goGo() {
      const result = await go();
    }
    // goGo().catch(handleError);

    // you can also handle orders with a higher order function

    //

    function makeSafe(fn, errorHandler) {
      return function () {
        fn().catch(errorHandler);
      };
    }

    go(); // unsafe

    const safeGo = makeSafe(go, handleError);

    safeGo();
  </script>
</body>

</html>